# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np

# original 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape to 2D array with 2 rows
arr_2d = arr.reshape(2, -1)

print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
import numpy as np

# two arrays to be stacked vertically
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.array([1, 1, 1, 1, 1])

# stack arrays vertically
arr_stacked = np.vstack((arr1, arr1, arr2, arr2))

print(arr_stacked)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
import numpy as np

# two arrays to be stacked horizontally
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.array([1, 1, 1, 1, 1])

# stack arrays horizontally
arr_stacked = np.hstack((arr1.reshape(-1,1), arr2.reshape(-1,1)))

print(arr_stacked)


[[0 1]
 [1 1]
 [2 1]
 [3 1]
 [4 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
import numpy as np

# 2D array to be flattened
arr_2d = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

# flatten the array
arr_flat = arr_2d.flatten()

print(arr_flat)


[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [10]:
import numpy as np

# array with higher dimensions to be flattened
arr_higher_dim = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]], [[12, 13, 14], [15, 16, 17]]])

# flatten the array
arr_flat = arr_higher_dim.flatten()

print(arr_flat)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
import numpy as np

# 1D array to be reshaped
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# reshape the array into a 2D array with 5 rows and 3 columns
arr_2d = arr_1d.reshape(5, 3)

print(arr_2d)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
import numpy as np

# create a 5x5 array
arr = np.arange(25).reshape((5, 5))
print (arr) # print 5 X 5 array

# find the square of the array
arr_squared = np.square(arr)

print(arr_squared)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [16]:
import numpy as np

# create a 5x6 array
arr = np.random.rand(5, 6)
print (arr) # print 5 X 6 array

# find the square of the array
arr_mean = np.mean(arr)

print(arr_mean)


[[0.0214798  0.20659707 0.96026919 0.39369111 0.03550061 0.03048378]
 [0.66695838 0.7420803  0.64142265 0.87521043 0.94029153 0.04543292]
 [0.28057608 0.79267635 0.73476749 0.61913267 0.08191474 0.10878368]
 [0.85453841 0.21701207 0.94101183 0.31912628 0.75262189 0.4141428 ]
 [0.42178543 0.6300865  0.71173568 0.55378083 0.81598743 0.91906001]]
0.5242719309560228


## Question:9

### Find the standard deviation of the previous array in Q8?

In [17]:
import numpy as np

# create a 5x6 array
arr = np.random.rand(5, 6)
print (arr) # print 5 X 6 array

# find the square of the array
arr_std = np.std(arr)

print(arr_std)


[[0.9828831  0.62198829 0.21243341 0.4298278  0.79658415 0.00730099]
 [0.99650982 0.87525976 0.72548659 0.44922125 0.64866894 0.18613837]
 [0.66045374 0.44224055 0.96551338 0.12597559 0.29288785 0.7748538 ]
 [0.01899083 0.37613985 0.38806815 0.83280157 0.20147069 0.20503681]
 [0.20549677 0.74254888 0.46782695 0.1900714  0.8037935  0.77995263]]
0.2992109509159882


## Question:10

### Find the median of the previous array in Q8?

In [18]:
import numpy as np

# create a 5x6 array
arr = np.random.rand(5, 6)
print (arr) # print 5 X 6 array

# find the square of the array
arr_median = np.median(arr)

print(arr_median)

[[0.91085245 0.98503971 0.95049172 0.18266076 0.75385805 0.88462928]
 [0.37990397 0.21911499 0.88354783 0.99472751 0.64654449 0.39983183]
 [0.69397336 0.66407685 0.72922811 0.15490678 0.02329789 0.40248451]
 [0.18300061 0.99566073 0.25936688 0.78905469 0.07257485 0.45595535]
 [0.78203885 0.2678216  0.98499998 0.17954768 0.81416318 0.18979161]]
0.6553106733747553


## Question:11

### Find the transpose of the previous array in Q8?

In [19]:
import numpy as np

# create a 5x6 array
arr = np.random.rand(5, 6)
print (arr) # print 5 X 6 array

# find the square of the array
arr_transpose = np.transpose(arr)

print(arr_transpose)

[[0.43946556 0.21549519 0.47310592 0.93559757 0.08889249 0.87098225]
 [0.46386805 0.5605251  0.94529567 0.01270569 0.59252331 0.01833919]
 [0.44720907 0.35218806 0.52721259 0.80589302 0.32241718 0.56574278]
 [0.8104078  0.92280999 0.18245397 0.90232935 0.99494798 0.36131635]
 [0.16863441 0.9680513  0.82482176 0.50396948 0.97670865 0.65313613]]
[[0.43946556 0.46386805 0.44720907 0.8104078  0.16863441]
 [0.21549519 0.5605251  0.35218806 0.92280999 0.9680513 ]
 [0.47310592 0.94529567 0.52721259 0.18245397 0.82482176]
 [0.93559757 0.01270569 0.80589302 0.90232935 0.50396948]
 [0.08889249 0.59252331 0.32241718 0.99494798 0.97670865]
 [0.87098225 0.01833919 0.56574278 0.36131635 0.65313613]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [23]:
import numpy as np

# create a 4x4 array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# find the sum of diagonal elements
diag_sum = np.trace(arr)

print(diag_sum)


34


## Question:13

### Find the determinant of the previous array in Q12?

In [22]:
import numpy as np

# create a 4x4 array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# find the determinant of the array
det = np.linalg.det(arr)

print(det)

-1.820448242817726e-31


## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
import numpy as np

# create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# find the 5th and 95th percentile
p5 = np.percentile(arr, 5)
p95 = np.percentile(arr, 95)

print(p5, p95)


1.45 9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [31]:
import numpy as np

# create an array with null values
arr = np.array([1, 2, np.nan, 4, None])

# convert the array to float type
arr_float = arr.astype(np.float64)

# check if the array has any null values
has_null = np.any(np.isnan(arr_float))

print(has_null)



True
