Problem  1

Convert a 1D array to a 2D array with 2 rows

Input:
```
np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```



In [1]:
import numpy as np

a = np.arange(10)
b = a.reshape(2, -1)  # the -1 indicates that numpy should infer the number of columns

print(b)


[[0 1 2 3 4]
 [5 6 7 8 9]]


Problem  2

Extract all odd numbers from arr

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```



Problem  3

Replace all odd numbers in arr with -1

```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Output:


```
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```



In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# boolean indexing to extract odd numbers
odd_nums = arr[arr % 2 != 0]

print(odd_nums)


[1 3 5 7 9]


Problem  4

Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Desired Output:

```
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```




In [3]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# create a new array with odd numbers replaced by -1
out = np.where(arr % 2 != 0, -1, arr)

print(out)
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


Problem  5

Stack arrays a and b vertically

Input



```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```




In [4]:
import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# stack arrays a and b vertically
out = np.vstack((a, b))

print(out)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Problem  6

Stack the arrays a and b horizontally.

Input


```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```


Desired Output:



```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```




In [5]:
import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# stack arrays a and b horizontally
out = np.hstack((a, b))

print(out)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Problem  7

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:



```
a = np.array([1,2,3])
```


Desired Output:



```
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```




In [6]:
import numpy as np

a = np.array([1, 2, 3])

# repeat each element of a three times
a_repeated = np.repeat(a, 3)

# tile the repeated array three times
a_tiled = np.tile(a_repeated, 3)

print(a_tiled)


[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


Problem  8

From array a remove all items present in array b

Input:


```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:

```
array([1,2,3,4])
```




In [7]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# remove all items present in b from a
out = np.setdiff1d(a, b)

print(out)


[1 2 3 4]


Problem  9

Get the positions where elements of a and b match

Input:



```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


Desired Output:



```
(array([1, 3, 5, 7]),)
```



In [8]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# get the positions where elements of a and b match
out = np.where(a == b)

print(out)


(array([1, 3, 5, 7], dtype=int64),)


Problem  10

Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```

Output:



```
array([[1, 0, 2],
      [4, 3, 5],
      [7, 6, 8]])
```




In [9]:
import numpy as np

arr = np.arange(9).reshape(3, 3)

# swap columns 1 and 2
arr[:, [1, 0]] = arr[:, [0, 1]]

print(arr)


[[1 0 2]
 [4 3 5]
 [7 6 8]]


Problem  11

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

Input:


```
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```


In [10]:
import numpy as np

np.random.seed(100)
a = np.random.uniform(1, 50, 20)

# replace values greater than 30 with 30 and less than 10 with 10
a = np.clip(a, 10, 30)

print(a)


[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


Problem  12

Compute the counts of unique values row-wise.

Input:



```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```



Desired Output:



```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```



In [14]:
import numpy as np

np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

# Count unique values row-wise
counts = [np.unique(row, return_counts=True)[1] for row in arr]
print(counts)


[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[array([1, 2, 1, 1, 1, 2, 2], dtype=int64), array([2, 1, 3, 1, 1, 1, 1], dtype=int64), array([3, 2, 3, 1, 1], dtype=int64), array([1, 2, 1, 1, 2, 1, 2], dtype=int64), array([2, 2, 2, 1, 1, 1, 1], dtype=int64), array([1, 1, 1, 1, 1, 2, 2, 1], dtype=int64)]


Problem  13

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# create example array
arr = np.array([0, 1, 2, 1, 0])

# create and fit encoder
encoder = OneHotEncoder(sparse=False)
encoder.fit(arr.reshape(-1, 1))

# transform array
onehot = encoder.transform(arr.reshape(-1, 1))

print(onehot)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


Problem  14

Create the ranks for the given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]
```

Desired output:

```
[4 2 6 0 8 7 9 3 5 1]
```

In [16]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]

# compute the ranks
ranks = a.argsort().argsort()
print(ranks)
#> [4 2 6 0 8 7 9 3 5 1]


[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


Problem  15

Create a rank array of the same shape as a given numeric array a.

Input:



```
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]
```


Desired output:



```
#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```



In [17]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

# Get indices that would sort the array a
idx = a.argsort(axis=None).reshape(a.shape)

# Get indices that would sort the flattened array a
flat_idx = a.flatten().argsort()

# Get the sorted array by using flat_idx
rank = np.empty_like(flat_idx)
rank[flat_idx] = np.arange(flat_idx.size)

# Reshape rank array to the shape of a
rank = rank.reshape(a.shape)

# Add 1 to rank to start from 1
rank += 1

print(rank)


[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[ 5  3  7  1  9]
 [ 8 10  4  6  2]]


Problem  16

Compute the min-by-max for each row for given 2d numpy array

Input:

```
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])
```

Desired Output:

```
array([ 0.44444444,  0.125     ,  0.5       ,  1.        ,  0.11111111])
```

In [18]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

min_vals = np.min(a, axis=1)
max_vals = np.max(a, axis=1)

min_by_max = min_vals / max_vals
print(min_by_max)


[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0.44444444 0.125      0.5        1.         0.11111111]


Problem  17

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input
```
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]
```
Desired Output:
```
#> [False  True False  True False False  True  True  True  True]
```

In [21]:
import numpy as np

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

_, indices = np.unique(a, return_index=True)
print(np.full(a.shape[0], False))
print(np.full(a.shape[0], False))
print(np.full(indices.shape[0], True))
print(np.full(a.shape[0] - indices.shape[0], False))
print(np.concatenate((np.full(indices.shape[0], True), np.full(a.shape[0] - indices.shape[0], False))))



Array:  [0 0 3 0 2 4 2 2 2 2]
[False False False False False False False False False False]
[False False False False False False False False False False]
[ True  True  True  True]
[False False False False False False]
[ True  True  True  True False False False False False False]


Problem  18

Drop all nan values from a 1D numpy array

Input:
```
np.array([1,2,3,np.nan,5,6,7,np.nan])
```
Desired Output:
```
array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [22]:
import numpy as np

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

result = a[~np.isnan(a)]

print(result)


[1. 2. 3. 5. 6. 7.]


Problem 19

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```

In [23]:
import numpy as np

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Find indices where the value is greater than both neighbors
peak_indices = np.where((a[:-2] < a[1:-1]) & (a[1:-1] > a[2:]))[0] + 1

print(peak_indices)


[2 5]


Problem 20

Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


Input
```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

```
Desired Output:
```
#> [[2 2 2]
#>  [2 2 2]
#>  [2 2 2]]
```

In [24]:
import numpy as np

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])

result = a_2d - b_1d[:, np.newaxis]

print(result)


[[2 2 2]
 [3 3 3]
 [4 4 4]]


Problem 21

Find the index of 5th repetition of number 1 in x.

Input:

```
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```



In [25]:
import numpy as np

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

# Find the indices of all occurrences of 1 in x
indices = np.where(x == 1)[0]

if len(indices) >= 5:
    # Find the index of the 5th repetition of 1
    fifth_index = indices[4]
    print(fifth_index)
else:
    print("There are less than 5 occurrences of 1 in x.")


8


Problem 22

Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [26]:
import numpy as np

a = np.arange(5, 5 + 3*10, 3)
print(a)


[ 5  8 11 14 17 20 23 26 29 32]


Problem 23

 From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

Input:
```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

Desired Output:
```
#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [28]:
import numpy as np

arr = np.arange(15)
window_size = 4
stride = 2

# Calculate the shape of the output array
out_shape = ((arr.size - window_size) // stride) + 1, window_size

# Calculate the strides of the input array to get the desired output
strides = arr.strides[0] * stride, arr.strides[0]

# Use as_strided function to get the desired output
out = np.lib.stride_tricks.as_strided(arr, shape=out_shape, strides=strides)

print(out)



[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
